### ISSUE TITLE
[BUG] Le GDI est inaccessible depuis une autre machine du réseau.

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/GDI-App-Issues#3]
**Décrire l'incident**
Le GDI est inaccessible depuis une autre machine du réseau.
Cela rend l'outil inutilisable pour les clients.

**Comment by jchable** [comment]
@fdanielsfc est-ce que tu aurais plus de détails, ce souci me semble être un souci de configuration de machine/réseau (proxy web ?) plus que de l'application qui ne bloque aucune requête entrante. Donc soit du côté de IIS, soit du proxy, soit du réseau. Est-ce que tu aurais plus d'infos sur cette anomalie à nous fournir ?

**Comment by fdanielsfc** [comment]
Je remet l'historique du soucis;

Si on ce connecte sur le serveur GDI, aucun soucis. Mais si on essaye de ce connecter depuis une autre machine en HTTPS on a cette erreur :
![pic1](https://user-images.githubusercontent.com/89943417/134835573-8b27dac3-c7bc-4bcf-96c7-fb4b5aa5e8f0.png)

Le port est bien ouvert entre le client et le serveur.
La configuration du serveur IIS :
![pic2](https://user-images.githubusercontent.com/89943417/134835591-dfd92170-2b1b-4526-8337-7b4115a0dac2.png)


A priori on a le meme soucis à la SGCB.

**Comment by fdanielsfc** [comment]
Retour de Christophe :

Le problème provient du fait que l’URL de l’API diffère sur l’environnement du client par rapport à celle qui a été utilisée pour générer le package de l’APP.
Ce souci a été identifié depuis un moment et a été corrigé en externalisant la configuration de l’API au niveau de l’APP.
Toutefois, la version 4.0.8 n’intègre pas cette correction.

Vu avec Sylver pour une intervention rapide chez les clients afin de gagner du temps en évitant de déployer une nouvelle version de l’APP.

**Comment by fdanielsfc** [comment]
Mon retour :

Si il existe un correctif pour cette fonction (et d’autres ?) il serai intéressant de communiquer dessus et de me fournir une version débuguée pour me permettre d’être autonome sur l’installation chez les clients.

Les client comprendront mal que tu doivent passer chez eux pour débuguer une application qu’on vient juste d’installer.
En effet une « intervention rapide » n’est pas si simple chez la plupart des clients. Cela implique différentes différentes choses : création d’un compte d’acces, badges, signature de clause de confidentialité…

Et avec le nombre de clients qui va augmenter (PIL, BNC et Mairie prévus rapidement) cela va engendrer pour toi une surcharge de travail qu’il ne sera certainement pas possible de facturer.

**Comment by jchable** [comment]
@fdanielsfc merci pour tous ces détails. Pour faire suite à notre échange, j'ai en effet fait un échange avec Christophe et on reboucle comme évoqué avec Sylver/Christophe, il est nécessaire que vous puissiez travailler ensemble. il s'agit d'une situation assez exceptionnelle, dans ce cas, Christophe interviendra à distance via une tierce personne de SF2i pour tester cette méthode de contournement, et ainsi éviter les allers et retours incessant. Est-ce que tu penses que ce cas exact se reproduira chez d'autres clients ? (même version de l'app et même configuration)

**Comment by fdanielsfc** [comment]
N'ayant que cette version de l'app et etant une configuration classique, cela devrai arriver chez tous les clients.
Donc deja sur les prochains jours : SGCB, Enercal, CHS, PIL, Mairie, BNC.

**Comment by jchable** [comment]
@fdanielsfc je pense que chacun doit rester dans son périmètre d'expertise et de support, aussi pour le coup @cverons sera à même de faire une première intervention, si cela est industrialisable de façon simple et sans ambiguïté, on verra pour faire une documentation pour les prochains clients. Attendons d'avoir le retour de cette intervention dan sun premier temps.

@cverons : quand penses-tu pouvoir faire cette intervention ?

**Comment by fdanielsfc** [comment]
Cela me va, si cela est industriable j'attend une procédure.
Sinon la fourniture d'une nouvelle version de l'app debuggé.

**Comment by jchable** [comment]
> Cela me va, si cela est industriable j'attend une procédure.
> Sinon la fourniture d'une nouvelle version de l'app debuggé.

@cverons Je te laisse revenir vers @fdanielsfc suite à ton intervention, en fonction de la meilleure solution à donner pour les autres clients.

**Comment by sschorgen** [comment]
@fdanielsfc peux-tu fournir à @cverons des VPN afin qu'ils puissent intervenir ?
Merci

**Comment by fdanielsfc** [comment]
Bonjour @sschorgen je n'ai pas la maitrise ou les droits sur l'infrastructure du client pour pouvoir ou me permettre de donner des acces VPN. 
Le soucis étant général (pour tous les clients), connu et reproductible par @cverons,  il me semblerai préférable de préparer un patch sur l'infra de test/dev puis la fournir au client.
Cela éviterai  d'importuner le client.

@sschorgen si toutefois vous ne trouvez pas d'autres solutions que d'intervenir sur l'infrastructure du client, je te laisse voir avec ce dernier pour demander les accès appropriés.

**Comment by jchable** [comment]
@fdanielsfc Pour cette première correction, comme évoqué, l'intervention de @cverons me semble indispensable. On fera le point sur la solution à suivre pour les autres clients avec le feedback de celle-ci. Mais livrer un patch/procédure qui n'a pas été testé au moins une fois est trop cavalier et une perte de temps pour tout le monde.

**Comment by fdanielsfc** [comment]
Depuis la resolution du bug chez Enercal il est maintenant impossible de ce connecter depuis Firefox.
La connexion fonctionne sous Edge uniquement.
Ceci reste bloquant et doit etre pris en compte pour la v4.0.9 afin que celle ci fonctionne sur tous les navigateurs majeurs.
Merci.

**Comment by jchable** [comment]
@fdanielsfc Testé ce soir sans aucun souci pour afficher l'écran sous Firefox. L'app est compatible aec tous les navigateurs modernes. Certainement un souci au niveau du poste. Pour la prochaine fois, il faudrait que tu nous donnes une capture, URL, la version du navigateur, .. merci d'avance

**Comment by fdanielsfc** [comment]
Le soucis est uniquement pour l'acces au serveur Enercal depuis la modification de Christophe.
J'ai testé l'acces en local sur le serveur, depuis une autre serveur, et le client a testé depuis son poste, et ca ne marche pas non plus.
L'authentification echoue de maniere systematique depuis Firefox. As tu pu testé sur l'infra Enercal ?

**Comment by fdanielsfc** [comment]
![image](https://user-images.githubusercontent.com/89943417/135513495-f143c4af-9966-4eed-b5c6-026900b7f9f1.png)

**Comment by jchable** [comment]
@fdanielsfc Si cela fonctionne avec un navigateur comme Edge, cela devrait fonctionner avec n'importe lequel. Après test de la même version, cela fonctionne de notre côté.
Est-ce qu'il n'y a pas un plugin dans le navigateur qui empêche cela ? Est-ce que cela fonctionne avec un autre FF sur les postes ? Est-ce une version déployée par l'entreprise ?
