### ISSUE TITLE
[BUG] Création de ressource ne propose pas de choisir le type

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/GDI-APP-Issues#58]
**Version de l'application concernée**
4.0.9

**Décrire l'incident**
A la création de ressource, ne permet pas de choisir le type de ressource (type fichier par defaut).

**Comment le reproduire ?**
Depuis le menu ressources, cliquer sur "ajouter une ressource"
![image](https://user-images.githubusercontent.com/89943417/146881024-89a59cd7-9993-495a-9814-03f3f36e416e.png)

Le formulaire de création de ressource s'ouvre sur le type "fichier" sans possibilité de modification.
![image](https://user-images.githubusercontent.com/89943417/146881076-e5104d93-41a6-4fc8-bf76-838b33db2353.png)

L'ideal serai de proposer le choix comme lors du clic sur le bouton "ajouter une ressource" depuis la liste des ressources.

**Comment by jchable** [comment]
Disponible dans la vNext (v5.1), sous la forme d'un bouton déroulant avec choix fixe du type de ressource.

La v5.1 est en cours de refonte actuellement. Pas de date de release pour le moment, en attenter surtout de la validation des versions 4.x. Le plus rapidement la 4.x est clôturé, le plus rapidement nous pourront passer à la v5.

**Comment by alanmallegol** [comment]
En version 4.1.2 il y'a deux cas :

- Le bouton "Ajouter ressource" du menu ne propose pas le choix du type de ressource.

- Le bouton "Nouvelle ressource" de l'écran "Liste des ressources" propose le choix du type de ressource.
