### ISSUE TITLE
[BUG] Acces aux menus impossible

### ISSUE THREAD

**Issue by fdanielsfc** [GDI-NC/GDI-App-Issues#8]
**Décrire l'incident**
Sur le GDI en v4.0.9 il est impossible d'accéder aux menus des listes et des parametres et des delegations.

**Copies écran**
En cliquant sur le menu reste sur cet écran
![image](https://user-images.githubusercontent.com/89943417/135769418-06789672-af6a-4fea-93c2-8f8d7ded58f4.png)

**Informations complémentaires**
J'ai eu ce comportement sur le serveur de la Mairie aprés l'intégration des données.
J'ai donc supprimé la BDD et recréé une BDD vide avec la délégation par defaut. Le resultat est le meme, impossible d'acceder a ces menus.

**Comment by fdanielsfc** [comment]
Et evidemment il y a le meme comportement sur le serveur de Enercal.

**Comment by jchable** [comment]
@fdanielsfc En effet, bug corrigé pour la prochaine version. Cette release n'avait pas encore été testée comme précisé par @cverons dans son mail, quand on a des bugs fix comme ça, il en faudrait pas les déployer chez différents simultanément. @cverons devrait pouvoir rapidement fournir la correction, cette issue est en Haute priorité comme le montre l'historique plus haut.

**Comment by fdanielsfc** [comment]
Ok, a quel date est prévue la prochaine version stable incluant le fix de la 4.0.9 et celui de ce bug ?
